version: '3.3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  app:
    image: app
    build:
      context: .
    env_file:
      - .env
    ports:
    - "3000:3000"